[package]
name = "id3-image"
version = "0.1.0"
authors = ["Andrew Radev <andrey.radev@gmail.com>"]
edition = "2018"

[dependencies]
id3 = { git = "https://github.com/jameshurst/rust-id3" }
image = "0.21.0"
