version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.61.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"
